
CREATE TABLE DEMO
(
	USER_ID            VARCHAR2 NOT NULL,
	USER_NAME          VARCHAR2 NULL ,
	USER_COUNT         NUMBER NULL ,
	IS_USE             CHAR(1) NULL DEFAULT 'Y'
);

ALTER TABLE DEMO
	ADD CONSTRAINT  DEMO_PK PRIMARY KEY (USER_ID);